spring.application.name=nfedesktop
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sutil_nfe}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sutil_nfe}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sutil_nfe}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
